<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="edycjaAnkiet.aspx.cs" Inherits="ApGlosowanie.edytor.edycjaAnkiet" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
    <h1>Edytor ankiet</h1>
        <asp:Table runat="server">
            <asp:TableRow>
                <asp:TableCell>

                </asp:TableCell>
            </asp:TableRow>
        </asp:Table>
        <asp:GridView ID="gv_pytania" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True" DataKeyNames="Id" DataSourceID="sql_ds_pytania" EnableModelValidation="True">
            <Columns>
                <asp:BoundField DataField="Id" HeaderText="Id" ReadOnly="True" SortExpression="Id" Visible="False" />
                <asp:BoundField DataField="IdTestu" HeaderText="IdTestu" SortExpression="IdTestu" Visible="False" />
                <asp:BoundField DataField="Pytanie" HeaderText="Pytanie" SortExpression="Pytanie" />
                <asp:CheckBoxField DataField="WielWybor" HeaderText="WielWybor" SortExpression="WielWybor" />
                <asp:BoundField DataField="NumerPytania" HeaderText="NumerPytania" SortExpression="NumerPytania" />
                <asp:CheckBoxField DataField="WymaganaOdp" HeaderText="WymaganaOdp" SortExpression="WymaganaOdp" />
            </Columns>
        </asp:GridView>
        <asp:SqlDataSource ID="sql_ds_pytania" runat="server" ConnectionString="<%$ ConnectionStrings:cs_glosowanie %>" SelectCommand="SELECT * FROM [Pytania] WHERE ([IdTestu] = @IdTestu)">
            <SelectParameters>
                <asp:ControlParameter ControlID="hf_id_ankiety" Name="IdTestu" PropertyName="Value" Type="Int32" />
            </SelectParameters>
        </asp:SqlDataSource>
        <asp:GridView ID="gv_odpowiedzi" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True" DataKeyNames="Id" DataSourceID="sql_ds_odpowiedzi" EnableModelValidation="True">
            <Columns>
                <asp:BoundField DataField="Id" HeaderText="Id" ReadOnly="True" SortExpression="Id" />
                <asp:BoundField DataField="IdPytania" HeaderText="IdPytania" SortExpression="IdPytania" />
                <asp:BoundField DataField="Tekst" HeaderText="Tekst" SortExpression="Tekst" />
                <asp:BoundField DataField="LicznikGlosow" HeaderText="LicznikGlosow" SortExpression="LicznikGlosow" />
                <asp:BoundField DataField="NumerPytania" HeaderText="NumerPytania" SortExpression="NumerPytania" />
            </Columns>
        </asp:GridView>
        <asp:GridView ID="gv_ankiety" runat="server" AutoGenerateColumns="False" DataKeyNames="Id" DataSourceID="sql_ds_ankiety" EnableModelValidation="True" ShowFooter="True" OnRowUpdating="GridView1_RowUpdating" OnSelectedIndexChanged="gv_ankiety_SelectedIndexChanged">
            <Columns>
                <asp:CommandField ShowDeleteButton="True" ShowEditButton="True" ShowSelectButton="True" />
                <asp:TemplateField HeaderText="Id" SortExpression="Id">
                    <EditItemTemplate>
                        <asp:Label ID="Label1" runat="server" Text='<%# Eval("Id") %>'></asp:Label>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label1" runat="server" Text='<%# Bind("Id") %>'></asp:Label>
                    </ItemTemplate>
                    <FooterTemplate>
                        <asp:Button ID="bt_dodaj_ankiete" runat="server" Text="Button" />
                    </FooterTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Nazwa" SortExpression="Nazwa">
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBox1" runat="server" Text='<%# Bind("Nazwa") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label2" runat="server" Text='<%# Bind("Nazwa") %>'></asp:Label>
                    </ItemTemplate>
                    <FooterTemplate>
                        <asp:TextBox ID="tb_nazwa_ankiety" runat="server"></asp:TextBox>
                    </FooterTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Stan" SortExpression="Stan">
                    <EditItemTemplate>
                        <asp:DropDownList ID="ddl_stan_ankiety_edit" runat="server" SelectedValue='<%# Bind("Stan") %>'>
                            <asp:ListItem Text="A" Value ="0"></asp:ListItem>
                            <asp:ListItem Text="B" Value ="1"></asp:ListItem>
                            <asp:ListItem Text="C" Value ="2"></asp:ListItem>
                            <asp:ListItem Text="D" Value ="3"></asp:ListItem>
                        </asp:DropDownList>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label3" runat="server" Text='<%# Bind("Stan") %>'></asp:Label>
                    </ItemTemplate>
                    <FooterTemplate>
                        <asp:DropDownList ID="ddl_stan_ankiety_ins" runat="server">
                            <asp:ListItem Text="A" Value ="0"></asp:ListItem>
                            <asp:ListItem Text="B" Value ="1"></asp:ListItem>
                            <asp:ListItem Text="C" Value ="2"></asp:ListItem>
                            <asp:ListItem Text="D" Value ="3"></asp:ListItem>
                        </asp:DropDownList>
                    </FooterTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="DataZakonczenia" SortExpression="DataZakonczenia">
                    <EditItemTemplate>
                        <asp:Calendar ID="Calendar1" runat="server" SelectedDate='<%# Bind("DataZakonczenia") %>' VisibleDate='<%# Eval("DataZakonczenia") %>'></asp:Calendar>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label4" runat="server" Text='<%# Bind("DataZakonczenia") %>'></asp:Label>
                    </ItemTemplate>
                    <FooterTemplate>
                        <asp:TextBox ID="tb_data_zakonczenia" runat="server"></asp:TextBox>
                    </FooterTemplate>
                </asp:TemplateField>

                <asp:TemplateField HeaderText="Test">
                    <EditItemTemplate>
                    </EditItemTemplate>
                </asp:TemplateField>

            </Columns>
        </asp:GridView>
        <asp:SqlDataSource ID="sql_ds_ankiety" runat="server" ConnectionString="<%$ ConnectionStrings:cs_glosowanie %>" DeleteCommand="DELETE FROM [Ankiety] WHERE [Id] = @Id" InsertCommand="INSERT INTO [Ankiety] ([Id], [Nazwa], [Stan], [DataZakonczenia]) VALUES (@Id, @Nazwa, @Stan, @DataZakonczenia)" SelectCommand="SELECT * FROM [Ankiety]" UpdateCommand="UPDATE [Ankiety] SET [Nazwa] = @Nazwa, [Stan] = @Stan, [DataZakonczenia] = @DataZakonczenia WHERE [Id] = @Id" OnUpdating="sql_ds_ankiety_Updating">
            <DeleteParameters>
                <asp:Parameter Name="Id" Type="Int32" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="Id" Type="Int32" />
                <asp:Parameter Name="Nazwa" Type="String" />
                <asp:Parameter Name="Stan" Type="Int32" />
                <asp:Parameter Name="DataZakonczenia" Type="DateTime" />
                <asp:Parameter Name="Test" Type="String" />
            </InsertParameters>
            <UpdateParameters>
                <asp:Parameter Name="Nazwa" Type="String" />
                <asp:Parameter Name="Stan" Type="Int32" />
                <asp:Parameter Name="DataZakonczenia" Type="DateTime" />
                <asp:Parameter Name="Id" Type="Int32" />
            </UpdateParameters>
        </asp:SqlDataSource>
        <br />
        <asp:SqlDataSource ID="sql_ds_odpowiedzi" runat="server" ConnectionString="<%$ ConnectionStrings:cs_glosowanie %>" SelectCommand="SELECT * FROM [Odpowiedzi] WHERE ([IdPytania] = @IdPytania)">
            <SelectParameters>
                <asp:ControlParameter ControlID="hf_id_pytania" Name="IdPytania" PropertyName="Value" Type="Int32" />
            </SelectParameters>
        </asp:SqlDataSource>
        <asp:HiddenField ID="hf_id_ankiety" runat="server" />
        <asp:HiddenField ID="hf_id_pytania" runat="server" />
        <asp:HiddenField ID="XD" runat="server" Value="23" />
        <br />

    </div>
    </form>
</body>
</html>
